"""employees + kb.employee_id

Revision ID: 6a03f1a09e9c
Revises: 1afe2f0005f8
Create Date: 2026-06-17 11:51:57.023280
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6a03f1a09e9c"
down_revision: str | None = "1afe2f0005f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("github_username", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notice_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_employees_workspace_email", "employees", ["workspace_id", "email"], unique=True
    )
    op.create_index(op.f("ix_employees_workspace_id"), "employees", ["workspace_id"], unique=False)
    op.add_column("knowledge_bases", sa.Column("employee_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_knowledge_bases_employee_id"), "knowledge_bases", ["employee_id"], unique=False
    )
    op.create_foreign_key(
        None, "knowledge_bases", "employees", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "knowledge_bases", type_="foreignkey")
    op.drop_index(op.f("ix_knowledge_bases_employee_id"), table_name="knowledge_bases")
    op.drop_column("knowledge_bases", "employee_id")
    op.drop_index(op.f("ix_employees_workspace_id"), table_name="employees")
    op.drop_index("ix_employees_workspace_email", table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
